name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploy everything to the staging

    steps:
      - name: SSH into server
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} &> ~/ssh_key
          ssh -i  ~/ssh_key ubuntu@15.207.223.155
          sudo su -
          cd ci-next-app/ && git pull
          pnpm install
          pnpm run build
          pm2 restart fe-server
          pm2 restart http-server
          pm2 restart ws-server
